"""empty message

Revision ID: a25cb1f6595c
Revises: 0204b0f0a549
Create Date: 2018-02-22 18:58:30.511973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a25cb1f6595c'
down_revision = '0204b0f0a549'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('highscores', sa.Column('score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('highscores', 'score')
    # ### end Alembic commands ###
