"""empty message

Revision ID: b0d8d2406ab6
Revises: a25cb1f6595c
Create Date: 2018-02-22 19:21:40.311890

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b0d8d2406ab6'
down_revision = 'a25cb1f6595c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session')
    op.add_column('words', sa.Column('category', sa.String(), nullable=False))
    op.add_column('words', sa.Column('hint', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'hint')
    op.drop_column('words', 'category')
    op.create_table('session',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sessionToken', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('session', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='session_pkey')
    )
    # ### end Alembic commands ###
